<a href="https://colab.research.google.com/github/edoardochiarotti/class_datascience/blob/main/2024/02_Data-Cleaning/02_Data-Cleaning-Practice.ipynb" target="_blank" rel="noopener"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# PACKAGES
import numpy as np
import pandas as pd
import os
import re
import plotly.express as px

# Data Cleaning: Practice with Pandas

<img src='https://miro.medium.com/v2/resize:fit:720/format:webp/1*noQ6RX4O_IAGmPOyUbEr9Q.jpeg' width="500">

Source: [Data Profiling — Having that First Date with your Data](https://medium.com/codex/data-profiling-having-that-first-date-with-your-data-2e05de50fca7), 
Kirk Borne

## Content

>  Data Scientists spend 80% of their time on data collecting and data cleaning operations. 
>
> The remaining 20% , they complain about cleaning data! 

Start your complaining journey with this notebook! You will explore two datasets, namely Polity5 and Quality of Government (QOG) Environmental Indicators Dataset, which could be useful for your projects. 

You will use Pandas (derived from "panel data"), the go-to package for data analysis and manipulation. Its primary object, the `DataFrame` is extremely useful in wrangling data. You can read more about Pandas in the [documentation](https://pandas.pydata.org/docs/index.html), and should read the notebook "02_Data-Cleaning-Panda-Introduction" before starting this walkthrough. Since Pandas is one of the most used package, you can also find a ton of material online, answering any questions you might have. As always, there is no need to reinvent the wheel, and you should rely on the years of experience and knowledge of programmers who already faced similar issues you might encounter. 

**As good practice, we imported `pandas` and other packages at the top of this notebook, do not forget to run the top cell to import the necessary packages!**


- [Polity5](#polity5)  
    - [Discover Polity5](#discover-polity5)
    - [Select some variables](#select-polity5)
    - [Dealing with Missing Values](#missing-value-polity5)
    - [Removing duplicates](#removing-polity5)
    - [Exploring Polity2](#exploring-polity5)
- [Quality of Government (QOG) Environmental Indicators Dataset](#qog)  
    - [Discover QOG](#import-qog)
    - [Merge QOG and Polity5](#merge-qog)
    - [Further practise [optional]](#practising-qog)
- [Other dataset to explore](#data)

## Polity5 <a name="polity5"></a>

<img src='https://www.thinkpragati.com/wp-content/uploads/2017/03/democracy-comic.png' width="600">

Source: [Amit Varma](https://www.thinkpragati.com/think/brainstorm/802/democracy-vs-republic/attachment/democracy-comic/)

Polity5 is a widely used democracy scale. The raw data as well as the codebook are available [here](http://www.systemicpeace.org/inscrdata.html). 

For this walkthough, we have modified a bit the original version, for example adding iso3 code for countries. You can find the modified version [here](https://raw.githubusercontent.com/edoardochiarotti/class_datascience/main/2023/02_Data-Cleaning/data/polity2_iso3.csv).

### Discover Polity5 <a name="discover-polity5"></a>

- Import the csv 'polity2_iso3.csv' (file provided in the link [here](https://raw.githubusercontent.com/thurmboris/Data-Science_4_Sustainability/main/data/polity2_iso3.csv)) as a panda dataframe (ignore the warning message)

In [3]:
# Your code here...
url='https://raw.githubusercontent.com/thurmboris/Data-Science_4_Sustainability/main/data/polity2_iso3.csv'

df=pd.read_csv(url)

type(df)

/var/folders/md/rxyl046s0hq8wpj_rdqzd1b80000gn/T/ipykernel_5967/3555238521.py:4: DtypeWarning: Columns (0: durable, 1: prior, 2: emonth, 3: eday, 4: eyear, 5: eprec, 6: interim, 7: bmonth, 8: bday, 9: byear, 10: bprec, 11: post, 12: change, 13: d5, 14: sf, 15: regtrans) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(url)

pandas.DataFrame

- Display the first 10 rows to start exploring our dataset

In [5]:
# Your code here...

df.head(10)

,iso3,year,p5,cyear,ccode,scode,country,flag,fragment,democ,...,interim,bmonth,bday,byear,bprec,post,change,d5,sf,regtrans
0,NaN,1800,0,2711800,271,WRT,Wuerttemburg,0,NaN,0,...,NaN,1.0,1.0,1800.0,1.0,-7.0,88.0,1.0,NaN,NaN
1,NaN,1800,0,7301800,730,KOR,Korea,0,NaN,5,...,NaN,1.0,1.0,1800.0,1.0,1.0,88.0,1.0,NaN,NaN
2,NaN,1800,0,2451800,245,BAV,Bavaria,0,NaN,0,...,NaN,1.0,1.0,1800.0,1.0,-10.0,88.0,1.0,NaN,NaN
3,NaN,1801,0,7301801,730,KOR,Korea,0,NaN,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,1801,0,2711801,271,WRT,Wuerttemburg,0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,1801,0,2451801,245,BAV,Bavaria,0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,1802,0,7301802,730,KOR,Korea,0,NaN,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,1802,0,2711802,271,WRT,Wuerttemburg,0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,1802,0,2451802,245,BAV,Bavaria,0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,1803,0,7301803,730,KOR,Korea,0,NaN,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- Display the data types of all the variables included in the data.

In [9]:
# Your code here...
df.dtypes
print(len(df))

17574

Notice that Pandas is using different names for data types. Here is a description:

|Pandas type|Native Python type|Description|
|:-------|:-------|:----------|
|`object` | `string` | The most general dtype. Will be assigned to your column if column has mixed types (numbers and strings). |
|`int64` | `int` | Numeric characters. 64 refers to the memory allocated to hold this character. |
|`float64` | `float` | Numeric characters with decimals. If a column contains numbers and NaNs (see below), pandas will default to float64, in case your missing value has a decimal.|

When you need to convert one column to another type, one option is to rely on `astype`([Documentation](http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.astype.html)).

### Select some variables <a name="select-polity5"></a>

In the following, we will work with one of the variable included in the dataset, namely "polity2". 

- In the [user manual of Polity5](https://www.systemicpeace.org/inscrdata.html), go and read section 2 *Indicators of Democracy and Autocracy (Composite Indices)* to better understand our variable. What do the values in "polity2" represent?

- Using `loc` ([Documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html)), create a subset dataframe that contains the variables 'iso3', 'country', 'year', 'polity2' and display it. How many observations (i.e., rows) do we have?

In [10]:
# Your code here...
df['polity2'].head()

subset_df = df.loc[:, ["iso3", "country", "year", "polity2"]]

display(subset_df)

      iso3       country  year  polity2
0      NaN  Wuerttemburg  1800     -7.0
1      NaN         Korea  1800      1.0
2      NaN       Bavaria  1800    -10.0
3      NaN         Korea  1801      1.0
4      NaN  Wuerttemburg  1801     -7.0
...    ...           ...   ...      ...
17569  ZWE      Zimbabwe  2014      4.0
17570  ZWE      Zimbabwe  2015      4.0
17571  ZWE      Zimbabwe  2016      4.0
17572  ZWE      Zimbabwe  2017      4.0
17573  ZWE      Zimbabwe  2018      4.0

[17574 rows x 4 columns]

### Dealing with Missing Values <a name="missing-value-polity5"></a>

Ok, now that we have selected our first ingredients, we need to start cleaning our dataset.

One of the first step is to identify and deal with missing values, `NaN`. `NaN` stands for **Not a Number**, and it can be interpreted as a value that is undefined or unrepresentable. When you import csv data, the following values will be interpreted as `NaN`: ‘’, ‘#N/A’, ‘#N/A N/A’, ‘#NA’, ‘-1.#IND’, ‘-1.#QNAN’, ‘-NaN’, ‘-nan’, ‘1.#IND’, ‘1.#QNAN’, ‘<NA>’, ‘N/A’, ‘NA’, ‘NULL’, ‘NaN’, ‘n/a’, ‘nan’, ‘null’. 
    
The `isna()` method ([Documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isna.html)) allows to detect `NaN`. It returns a dataframe of the same size that indicates if a value is a `NaN` with `True`, or not with `False`.

- How many missing values do we have for each variable?

*Hints*: Remember that `True` is associated with the value `1` and `False` with the value `0`, so you can sum over a column of `True`/`False` to  count the number of `True` statement. You can sum over a dataframe column using the method `.sum()` ([Documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sum.html)).

In [11]:
# Your code here...
missing_values = subset_df.isna().sum()

print(missing_values)

iso3       1270
country       0
year          0
polity2     263
dtype: int64

What should we do with the missing missing values? There are several potential strategies:
1. Delete the observations (rows) with missing values;
2. Impute missing values based on our knowledge;
3. Predict the missing values using, for instance, an algorithm. 

The strategy we decide to implement depends on the context! And **you should always justify and carefully document your assumptions.**

Ok let's try to gain further information on our missing values, starting with the variable "iso3".

- Create a subset dataframe containing only the observations with missing "iso3" values. Note: you should use the `loc` method.
- With the method `.sort_values()` ([Documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html)), sort your subset dataframe by "year" and "country".
- Display your subset dataframe. One option is to to print your dataframe as string, using the method `.to_string()` ([Documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_string.html))

In [13]:
# Your code here...

missing_iso3 = subset_df.loc[subset_df["iso3"].isna()]

missing_iso3 = missing_iso3.sort_values(
    by=["year", "country"]
)

print(missing_iso3.to_string())

     iso3                country  year  polity2
2     NaN                Bavaria  1800    -10.0
1     NaN                  Korea  1800      1.0
0     NaN           Wuerttemburg  1800     -7.0
5     NaN                Bavaria  1801    -10.0
3     NaN                  Korea  1801      1.0
4     NaN           Wuerttemburg  1801     -7.0
8     NaN                Bavaria  1802    -10.0
6     NaN                  Korea  1802      1.0
7     NaN           Wuerttemburg  1802     -7.0
10    NaN                Bavaria  1803    -10.0
9     NaN                  Korea  1803      1.0
11    NaN           Wuerttemburg  1803     -7.0
12    NaN                Bavaria  1804    -10.0
13    NaN                  Korea  1804      1.0
14    NaN           Wuerttemburg  1804     -7.0
17    NaN                Bavaria  1805    -10.0
16    NaN                  Korea  1805      1.0
15    NaN           Wuerttemburg  1805     -7.0
18    NaN                Bavaria  1806    -10.0
20    NaN                  Korea  1806      1.0
21    NaN                 Saxony  1806    -10.0
19    NaN           Wuerttemburg  1806     -7.0
24    NaN                Bavaria  1807    -10.0
22    NaN                  Korea  1807      1.0
23    NaN                 Saxony  1807    -10.0
25    NaN           Wuerttemburg  1807     -7.0
27    NaN                Bavaria  1808    -10.0
28    NaN                  Korea  1808      1.0
26    NaN                 Saxony  1808    -10.0
29    NaN           Wuerttemburg  1808     -7.0
31    NaN                Bavaria  1809    -10.0
30    NaN                  Korea  1809      1.0
33    NaN                 Saxony  1809    -10.0
32    NaN           Wuerttemburg  1809     -7.0
35    NaN                Bavaria  1810    -10.0
37    NaN                  Korea  1810      1.0
36    NaN                 Saxony  1810    -10.0
34    NaN           Wuerttemburg  1810     -7.0
38    NaN                Bavaria  1811    -10.0
41    NaN                  Korea  1811      1.0
40    NaN                 Saxony  1811    -10.0
39    NaN           Wuerttemburg  1811     -7.0
43    NaN                Bavaria  1812    -10.0
45    NaN                  Korea  1812      1.0
42    NaN                 Saxony  1812    -10.0
44    NaN           Wuerttemburg  1812     -7.0
49    NaN                Bavaria  1813    -10.0
48    NaN                  Korea  1813      1.0
46    NaN                 Saxony  1813      NaN
47    NaN           Wuerttemburg  1813     -7.0
51    NaN                Bavaria  1814    -10.0
52    NaN                  Korea  1814      1.0
50    NaN                 Saxony  1814      NaN
53    NaN           Wuerttemburg  1814     -7.0
59    NaN                Bavaria  1815    -10.0
55    NaN                  Korea  1815      1.0
58    NaN                 Modena  1815    -10.0
54    NaN                  Parma  1815    -10.0
57    NaN               Sardinia  1815    -10.0
60    NaN                 Saxony  1815    -10.0
56    NaN                Tuscany  1815    -10.0
61    NaN           Wuerttemburg  1815     -7.0
67    NaN                Bavaria  1816    -10.0
65    NaN                  Korea  1816      1.0
69    NaN                 Modena  1816    -10.0
70    NaN                  Parma  1816    -10.0
66    NaN               Sardinia  1816    -10.0
68    NaN                 Saxony  1816    -10.0
63    NaN                Tuscany  1816    -10.0
64    NaN           Two Sicilies  1816    -10.0
62    NaN           Wuerttemburg  1816     -7.0
76    NaN                Bavaria  1817    -10.0
75    NaN                  Korea  1817      1.0
77    NaN                 Modena  1817    -10.0
71    NaN                  Parma  1817    -10.0
72    NaN               Sardinia  1817    -10.0
78    NaN                 Saxony  1817    -10.0
79    NaN                Tuscany  1817    -10.0
74    NaN           Two Sicilies  1817    -10.0
73    NaN           Wuerttemburg  1817     -7.0
83    NaN                Bavaria  1818     -9.0
87    NaN                  Korea  1818      1.0
82    NaN                 Modena  1818    -10.0
86    NaN                  Parma  1818    -10.0
88    NaN               Sardinia  1818    -10.0
85    NaN                 Saxony  1818    -10.0
81    NaN                Tuscany  1818    -10.0
80    NaN           Two Sicilies  1818    -10.0
84    NaN           Wuerttemburg  1818     -7.0
89    NaN                  Baden  1819     -7.0
93    NaN                Bavaria  1819     -9.0
97    NaN                  Korea  1819      1.0
94    NaN                 Modena  1819    -10.0
95    NaN                  Parma  1819    -10.0
96    NaN               Sardinia  1819    -10.0
90    NaN                 Saxony  1819    -10.0
98    NaN                Tuscany  1819    -10.0
91    NaN           Two Sicilies  1819    -10.0
92    NaN           Wuerttemburg  1819     -4.0
107   NaN                  Baden  1820     -7.0
108   NaN                Bavaria  1820     -9.0
100   NaN                  Korea  1820      1.0
103   NaN                 Modena  1820    -10.0
99    NaN                  Parma  1820    -10.0
102   NaN               Sardinia  1820    -10.0
101   NaN                 Saxony  1820    -10.0
104   NaN                Tuscany  1820    -10.0
106   NaN           Two Sicilies  1820     -6.0
105   NaN           Wuerttemburg  1820     -4.0
114   NaN                  Baden  1821     -7.0
111   NaN                Bavaria  1821     -9.0
112   NaN          Gran Colombia  1821     -1.0
117   NaN                  Korea  1821      1.0
118   NaN                 Modena  1821    -10.0
109   NaN                  Parma  1821    -10.0
119   NaN               Sardinia  1821    -10.0
113   NaN                 Saxony  1821    -10.0
116   NaN                Tuscany  1821    -10.0
110   NaN           Two Sicilies  1821    -10.0
115   NaN           Wuerttemburg  1821     -4.0
122   NaN                  Baden  1822     -7.0
120   NaN                Bavaria  1822     -9.0
126   NaN          Gran Colombia  1822     -1.0
127   NaN                  Korea  1822      1.0
124   NaN                 Modena  1822    -10.0
121   NaN                  Parma  1822    -10.0
128   NaN               Sardinia  1822    -10.0
125   NaN                 Saxony  1822    -10.0
123   NaN                Tuscany  1822    -10.0
130   NaN           Two Sicilies  1822    -10.0
129   NaN           Wuerttemburg  1822     -4.0
135   NaN                  Baden  1823     -7.0
141   NaN                Bavaria  1823     -9.0
137   NaN          Gran Colombia  1823     -1.0
131   NaN                  Korea  1823      1.0
133   NaN                 Modena  1823    -10.0
138   NaN                  Parma  1823    -10.0
134   NaN               Sardinia  1823    -10.0
139   NaN                 Saxony  1823    -10.0
132   NaN                Tuscany  1823    -10.0
136   NaN           Two Sicilies  1823    -10.0
140   NaN           Wuerttemburg  1823     -4.0
142   NaN                  Baden  1824     -7.0
151   NaN                Bavaria  1824     -9.0
143   NaN          Gran Colombia  1824     -1.0
146   NaN                  Korea  1824      1.0
145   NaN                 Modena  1824    -10.0
153   NaN                  Parma  1824    -10.0
149   NaN               Sardinia  1824    -10.0
152   NaN                 Saxony  1824    -10.0
148   NaN                Tuscany  1824    -10.0
150   NaN           Two Sicilies  1824    -10.0
147   NaN     United Province CA  1824      2.0
144   NaN           Wuerttemburg  1824     -4.0
165   NaN                  Baden  1825     -7.0
157   NaN                Bavaria  1825     -9.0
159   NaN          Gran Colombia  1825     -1.0
163   NaN                  Korea  1825      1.0
161   NaN                 Modena  1825    -10.0
156   NaN                  Parma  1825    -10.0
164   NaN               Sardinia  1825    -10.0
158   NaN                 Saxony  1825    -10.0
162   NaN                Tuscany  1825    -10.0
160   NaN           Two Sicilies  1825    -10.0
154   NaN     United Province CA  1825      2.0
155   NaN           Wuerttemburg  1825     -4.0
170   NaN                  Baden  1826     -7.0
176   NaN                Bavaria  1826     -9.0
169   NaN          Gran Colombia  1826     -1.0
167   NaN                  Korea  1826      1.0
173   NaN                 Modena  1826    -10.0
166   NaN                  Parma  1826    -10.0
174   NaN               Sardinia  1826    -10.0
175   NaN                 Saxony  1826    -10.0
177   NaN                Tuscany  1826    -10.0
171   NaN           Two Sicilies  1826    -10.0
172   NaN     United Province CA  1826      2.0
168   NaN           Wuerttemburg  1826     -4.0
181   NaN                  Baden  1827     -7.0
186   NaN                Bavaria  1827     -9.0
188   NaN          Gran Colombia  1827     -1.0
184   NaN                  Korea  1827      1.0
182   NaN                 Modena  1827    -10.0
185   NaN                  Parma  1827    -10.0
178   NaN               Sardinia  1827    -10.0
183   NaN                 Saxony  1827    -10.0
187   NaN                Tuscany  1827    -10.0
179   NaN           Two Sicilies  1827    -10.0
180   NaN     United Province CA  1827      2.0
189   NaN           Wuerttemburg  1827     -4.0
192   NaN                  Baden  1828     -7.0
198   NaN                Bavaria  1828     -9.0
199   NaN          Gran Colombia  1828     -5.0
194   NaN                  Korea  1828      1.0
197   NaN                 Modena  1828    -10.0
200   NaN                  Parma  1828    -10.0
191   NaN               Sardinia  1828    -10.0
195   NaN                 Saxony  1828    -10.0
201   NaN                Tuscany  1828    -10.0
196   NaN           Two Sicilies  1828    -10.0
193   NaN     United Province CA  1828      2.0
190   NaN           Wuerttemburg  1828     -4.0
207   NaN                  Baden  1829     -7.0
204   NaN                Bavaria  1829     -9.0
205   NaN          Gran Colombia  1829     -5.0
210   NaN                  Korea  1829      1.0
212   NaN                 Modena  1829    -10.0
206   NaN                  Parma  1829    -10.0
209   NaN               Sardinia  1829    -10.0
211   NaN                 Saxony  1829    -10.0
208   NaN                Tuscany  1829    -10.0
203   NaN           Two Sicilies  1829    -10.0
213   NaN     United Province CA  1829      2.0
202   NaN           Wuerttemburg  1829     -4.0
222   NaN                  Baden  1830     -7.0
220   NaN                Bavaria  1830     -9.0
214   NaN          Gran Colombia  1830     -5.0
225   NaN                  Korea  1830      1.0
221   NaN                 Modena  1830    -10.0
223   NaN                  Parma  1830    -10.0
215   NaN               Sardinia  1830    -10.0
219   NaN                 Saxony  1830    -10.0
224   NaN                 Serbia  1830     -7.0
226   NaN                Tuscany  1830    -10.0
216   NaN           Two Sicilies  1830    -10.0
218   NaN     United Province CA  1830      2.0
217   NaN           Wuerttemburg  1830     -4.0
231   NaN                  Baden  1831     -7.0
236   NaN                Bavaria  1831     -9.0
228   NaN          Gran Colombia  1831     -5.0
239   NaN                  Korea  1831      1.0
238   NaN                 Modena  1831    -10.0
233   NaN                  Parma  1831    -10.0
234   NaN               Sardinia  1831    -10.0
237   NaN                 Saxony  1831     -7.0
230   NaN                 Serbia  1831     -7.0
235   NaN                Tuscany  1831    -10.0
229   NaN           Two Sicilies  1831    -10.0
232   NaN     United Province CA  1831      2.0
227   NaN           Wuerttemburg  1831     -4.0
245   NaN                  Baden  1832     -7.0
250   NaN                Bavaria  1832     -9.0
249   NaN          Gran Colombia  1832     -5.0
246   NaN                  Korea  1832      1.0
243   NaN                 Modena  1832    -10.0
240   NaN                  Parma  1832    -10.0
241   NaN               Sardinia  1832    -10.0
242   NaN                 Saxony  1832     -7.0
252   NaN                 Serbia  1832     -7.0
247   NaN                Tuscany  1832    -10.0
248   NaN           Two Sicilies  1832    -10.0
251   NaN     United Province CA  1832      2.0
244   NaN           Wuerttemburg  1832     -4.0
257   NaN                  Baden  1833     -7.0
264   NaN                Bavaria  1833     -9.0
258   NaN                  Korea  1833      1.0
260   NaN                 Modena  1833    -10.0
256   NaN                  Parma  1833    -10.0
254   NaN               Sardinia  1833    -10.0
263   NaN                 Saxony  1833     -7.0
261   NaN                 Serbia  1833     -7.0
262   NaN                Tuscany  1833    -10.0
259   NaN           Two Sicilies  1833    -10.0
253   NaN     United Province CA  1833      2.0
255   NaN           Wuerttemburg  1833     -4.0
265   NaN                  Baden  1834     -7.0
275   NaN                Bavaria  1834     -9.0
266   NaN                  Korea  1834      1.0
268   NaN                 Modena  1834    -10.0
274   NaN                  Parma  1834    -10.0
269   NaN               Sardinia  1834    -10.0
267   NaN                 Saxony  1834     -7.0
272   NaN                 Serbia  1834     -7.0
271   NaN                Tuscany  1834    -10.0
270   NaN           Two Sicilies  1834    -10.0
276   NaN     United Province CA  1834      2.0
273   NaN           Wuerttemburg  1834     -4.0
278   NaN                  Baden  1835     -7.0
277   NaN                Bavaria  1835     -9.0
288   NaN                  Korea  1835      1.0
283   NaN                 Modena  1835    -10.0
284   NaN                  Parma  1835    -10.0
279   NaN               Sardinia  1835    -10.0
285   NaN                 Saxony  1835     -7.0
286   NaN                 Serbia  1835     -7.0
280   NaN                Tuscany  1835    -10.0
282   NaN           Two Sicilies  1835    -10.0
287   NaN     United Province CA  1835      2.0
281   NaN           Wuerttemburg  1835     -4.0
293   NaN                  Baden  1836     -7.0
299   NaN                Bavaria  1836     -9.0
290   NaN                  Korea  1836      1.0
300   NaN                 Modena  1836    -10.0
291   NaN                  Parma  1836    -10.0
289   NaN               Sardinia  1836    -10.0
296   NaN                 Saxony  1836     -7.0
295   NaN                 Serbia  1836     -7.0
297   NaN                Tuscany  1836    -10.0
298   NaN           Two Sicilies  1836    -10.0
294   NaN     United Province CA  1836      2.0
292   NaN           Wuerttemburg  1836     -4.0
308   NaN                  Baden  1837     -7.0
310   NaN                Bavaria  1837     -9.0
309   NaN                  Korea  1837      1.0
305   NaN                 Modena  1837    -10.0
312   NaN                  Parma  1837    -10.0
304   NaN               Sardinia  1837    -10.0
302   NaN                 Saxony  1837     -7.0
301   NaN                 Serbia  1837     -7.0
307   NaN                Tuscany  1837    -10.0
311   NaN           Two Sicilies  1837    -10.0
306   NaN     United Province CA  1837      2.0
303   NaN           Wuerttemburg  1837     -4.0
322   NaN                  Baden  1838     -7.0
314   NaN                Bavaria  1838     -9.0
321   NaN                  Korea  1838      1.0
320   NaN                 Modena  1838    -10.0
317   NaN                  Parma  1838    -10.0
323   NaN               Sardinia  1838    -10.0
315   NaN                 Saxony  1838     -7.0
318   NaN                 Serbia  1838      2.0
319   NaN                Tuscany  1838    -10.0
316   NaN           Two Sicilies  1838    -10.0
324   NaN     United Province CA  1838      2.0
313   NaN           Wuerttemburg  1838     -4.0
334   NaN                  Baden  1839     -7.0
326   NaN                Bavaria  1839     -9.0
329   NaN                  Korea  1839      1.0
327   NaN                 Modena  1839    -10.0
330   NaN                  Parma  1839    -10.0
335   NaN               Sardinia  1839    -10.0
328   NaN                 Saxony  1839     -7.0
333   NaN                 Serbia  1839      2.0
331   NaN                Tuscany  1839    -10.0
332   NaN           Two Sicilies  1839    -10.0
325   NaN           Wuerttemburg  1839     -4.0
342   NaN                  Baden  1840     -7.0
346   NaN                Bavaria  1840     -8.0
338   NaN                  Korea  1840      1.0
339   NaN                 Modena  1840    -10.0
336   NaN                  Parma  1840    -10.0
337   NaN               Sardinia  1840    -10.0
343   NaN                 Saxony  1840     -8.0
344   NaN                 Serbia  1840      2.0
345   NaN                Tuscany  1840    -10.0
340   NaN           Two Sicilies  1840    -10.0
341   NaN           Wuerttemburg  1840     -4.0
350   NaN                  Baden  1841     -4.0
355   NaN                Bavaria  1841     -8.0
349   NaN                  Korea  1841      1.0
353   NaN                 Modena  1841    -10.0
351   NaN                  Parma  1841    -10.0
352   NaN               Sardinia  1841    -10.0
354   NaN                 Saxony  1841     -8.0
357   NaN                 Serbia  1841      2.0
347   NaN                Tuscany  1841    -10.0
348   NaN           Two Sicilies  1841    -10.0
356   NaN           Wuerttemburg  1841     -4.0
367   NaN                  Baden  1842     -4.0
358   NaN                Bavaria  1842     -8.0
360   NaN                  Korea  1842      1.0
368   NaN                 Modena  1842    -10.0
366   NaN                  Parma  1842    -10.0
361   NaN               Sardinia  1842    -10.0
359   NaN                 Saxony  1842     -8.0
363   NaN                 Serbia  1842      2.0
365   NaN                Tuscany  1842    -10.0
364   NaN           Two Sicilies  1842    -10.0
362   NaN           Wuerttemburg  1842     -4.0
371   NaN                  Baden  1843     -4.0
379   NaN                Bavaria  1843     -8.0
375   NaN                  Korea  1843      1.0
373   NaN                 Modena  1843    -10.0
372   NaN                  Parma  1843    -10.0
374   NaN               Sardinia  1843    -10.0
370   NaN                 Saxony  1843     -8.0
369   NaN                 Serbia  1843      2.0
377   NaN                Tuscany  1843    -10.0
378   NaN           Two Sicilies  1843    -10.0
376   NaN           Wuerttemburg  1843     -4.0
383   NaN                  Baden  1844     -4.0
384   NaN                Bavaria  1844     -8.0
385   NaN                  Korea  1844      1.0
389   NaN                 Modena  1844    -10.0
382   NaN                  Parma  1844    -10.0
381   NaN               Sardinia  1844    -10.0
388   NaN                 Saxony  1844     -8.0
387   NaN                 Serbia  1844      2.0
390   NaN                Tuscany  1844    -10.0
380   NaN           Two Sicilies  1844    -10.0
386   NaN           Wuerttemburg  1844     -4.0
399   NaN                  Baden  1845     -4.0
400   NaN                Bavaria  1845     -8.0
396   NaN                  Korea  1845      1.0
392   NaN                 Modena  1845    -10.0
397   NaN                  Parma  1845    -10.0
398   NaN               Sardinia  1845    -10.0
391   NaN                 Saxony  1845     -9.0
394   NaN                 Serbia  1845      2.0
395   NaN                Tuscany  1845    -10.0
401   NaN           Two Sicilies  1845    -10.0
393   NaN           Wuerttemburg  1845     -4.0
408   NaN                  Baden  1846     -4.0
402   NaN                Bavaria  1846     -8.0
403   NaN                  Korea  1846      1.0
406   NaN                 Modena  1846    -10.0
407   NaN                  Parma  1846    -10.0
411   NaN               Sardinia  1846    -10.0
404   NaN                 Saxony  1846     -9.0
410   NaN                 Serbia  1846      2.0
412   NaN                Tuscany  1846    -10.0
409   NaN           Two Sicilies  1846    -10.0
405   NaN           Wuerttemburg  1846     -4.0
423   NaN                  Baden  1847     -4.0
417   NaN                Bavaria  1847     -8.0

- What do you notice when looking at the list of countries? To make it easier, print the countries with missing "iso3". You can use the method `unique()` ([Documentation](https://pandas.pydata.org/docs/reference/api/pandas.unique.html)) to extract the unique values in a dataframe.

In [15]:
# Your code here...

countries_missing_iso3 = missing_iso3.unique(
    .loc[subset_df["iso3"].isna(), "country"]
)

print(countries_missing_iso3)

AttributeError: 'DataFrame' object has no attribute 'unique'

It seems that some of these "countries" are states that ceased to exist, either because they split (e.g., Czechoslovakia, Yugoslavia) or merged (e.g., Bavaria, Saxony). However, some still exist today (e.g., Ethiopia). We are going to explore what is happening with these countries.

The function `country_search` defines below will be useful. It takes as input a dataframe and a country name, and prints, independently of the casing, a dataframe with all the observations containing this country name:

In [ ]:
def country_search(df, country):
    df_out = df.loc[[bool(re.search(country, i, flags = re.IGNORECASE)) for i in df['country']],:]
    df_out = df_out.sort_values(by=['year'])
    print(df_out.to_string())

- Using the function `country_search` (do not forget to run the cell above), display the rows for which the column "country" contains the word "Serbia". By looking at the result, can you tell what happened to Serbia in 2006?

In [ ]:
# Your code here...

- Do the same for "vietnam"

In [ ]:
# Your code here...

The countries with missing iso3 values from 2011 onwards still exist today and might be needed for our analysis. Hence, instead of just deleting the observations, we are going to replace the nan iso3 with proper values.

- Create a list containing the (unique) countries with missing values from 2011 onwards

In [ ]:
# Your code here...

The iso3 code of these countries are: Ethiopia: "ETH", Montenegro: "MNE", Serbia: "SRB", Sudan-North: "SDN" and Vietnam: "VNM"

- For your "polity2" dataframe (dataframe obtained at the end of the previous section, , containing all the observations), replace `NaN` values in iso3 with correct iso3 for these 5 countries from 2011 onwards. Check that the substitution worked.

*Hint*: You could use a for loop, and, for instance, the function `zip` ([Documentation](https://docs.python.org/3/library/functions.html#zip))

In [ ]:
# Your code here...

- Drop the remaining rows which have `NaN` in "iso3" and display your new dataframe. How many obervations do we have?

In [ ]:
# Your code here...

### Removing duplicates <a name="removing-polity5"></a>

Another common operation of data cleaning consists in removing duplicate obervarions. We should, for instance, only have one polity2 value for a given iso3 (country) and year. Let's check if we have duplicates rows. 

One option is to use the method `.duplicated()` ([Documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.duplicated.html)), which returns `True` if the row has a duplicate and `False` otherwise.

- Create a new dataframe extracting the duplicated rows from the dataframe previously obtained. To do so, you can create an intermediate Series of Boolean with `.duplicated()`, and you should use as options `subset=['iso3', 'year']` to identify rows with the same iso3-year values, and `keep=False` to keep all duplicates
- Display your new dataframe

In [ ]:
# Your code here...

What should we do with these duplicates? It is worth looking at some obervations before and after the duplicates to get a better understanding.

- Extract the rows with iso3 equal to "MNE" and "SDN" after 2000 from the "polity2" dataframe (dataframe obtained at the end of previous section, after removing rows with NaN values)

In [ ]:
# Your code here...

South Sudan gained independence from Sudan in 2011. Hence, in our dataset, Sudan is called Sudan-North starting from 2011. We will drop the observation "Sudan-2011", and rename "Sudan-North" as "Sudan". Moreover, Kosovo does not have an official iso3 code and the state is only partially recognized. We could still make use of these observations, so we'll replace the Kosovo code with the unofficial "XXK".

In our "polity2" dataframe (dataframe obtained at the end of previous section, after removing rows with NaN values):
- Drop the observation with country "Sudan" and year 2011
- Remame "Sudan-North" as "Sudan"
- Replace the Kosovo iso3 code with "XXK"
- Check that we do not have any duplicated rows left

In [ ]:
# Your code here...

### Exploring Polity2 <a name="exploring-polity5"></a>

We'll now explore a bit the Polity2 variable.

- Display the first and last year included in the dataset

In [ ]:
# Your code here...

As mentioned in the documentation, Polity is a scale from -10 (complete autocracy) to 10 ("perfect" democracy). The index is computed as DEMOC-AUTOC, with DEMOC being a democracy score and AUTOC a autocracy score. More precisely each (DEMOC/AUTOC) is computed as sum of grades evaluating: "Competitiveness of Executive Recruitment", "Openness of Executive Recruitment", "Constraints on Chief Executive", "Regulation of participation", "Competitiveness of Participation".

- Print a sorted list of the (unique) "polity2" values

In [ ]:
# Your code here...

As you can see, there are values that are not between -10 and 10. As per the user manual: -66 and -88 corresponds respectively to "interuption" and "transition". What do you think we should do with these values?
1. One option would be to replace these values with NaN, since they are missing. 
2. Another would be to check if we could replace these values with others, more meaningful ones. For example, we could check the countries/years where these values appear, and if the indicator is stable the years before and after the interuption, then replace -66/-88 with the value taken from the years before/after. In such case, we would need to carefully justify our assumptions!

In this walkthrough, we'll go with option 1.

- Replace with values -66 and -88 with NaN. Hint, you can use `np.nan`. Check that your replacement worked.

In [ ]:
# Your code here...

Finally, as a teaser for next week, let's do a map of the number of observations per countries. You can simply run the code below. It groups the observation by iso3 code, and then create a map using the [plotly express module](https://plotly.com/python/plotly-express/).

In [ ]:
# !!! Replace df_pol2 with your dataframe name !!!

df_map = df_pol2.groupby(['iso3']).size().reset_index(name='counts')
fig = px.choropleth(df_map, locations='iso3',
                    locationmode='ISO-3',
                    color='counts', 
                    hover_name='iso3',
                    title = 'Number of polity2 observations per country',
                    color_continuous_scale=px.colors.sequential.Plasma)
fig.show()

## Quality of Government Environmental Indicators <a name="qog"></a>

<img src='https://www.economist.com/cdn-cgi/image/width=834,quality=80,format=auto/sites/default/files/images/2021/08/articles/main/20210814_wwd000.jpg' width="500">

Source: [Cartoon by Kevin KAL Kallaugher](https://www.kaltoons.com/about/), [The Economist](https://www.economist.com/the-world-this-week/2021/08/14/kals-cartoon)

The Quality of Government Environmental Indicators Dataset is a compilation of indicators measuring countries' environmental performance over time, including the presence and stringency of environmental policies, environmental outcomes (emissions, deforestation, etc.), and public opinion on the environment. Codebook and data are available [here](https://www.gu.se/en/quality-government/qog-data/data-downloads/environmental-indicators-dataset).

*Reference: Povitkina, Marina, Natalia Alvarado Pachon & Cem Mert Dalli. 2021. The Quality of Government Environmental Indicators Dataset, version Sep21. University of Gothenburg: The Quality of Government Institute, https://www.gu.se/en/quality-government*

### Discover QoG <a name="import-qog"></a>

- Import data from the Quality of Government Environmental Indicators Dataset and display the first 5 observations and shape. How many observations do we have? How many variables? 

*Hint*: When you go on the webpage of the Environmental Indicators Dataset, you can directly import from a URL by copying the link address of the dataset!

In [ ]:
# Your code here...

Check QoG codebook to discover all the available variables!

### Merge QoG and Polity5 <a name="merge-qog"></a>

We will try to merge the QoG and Polity5 dataset. To do so, we need to properly identify each observation, and the easiest in our case is to rely on the countries iso3 codes and year of observation. However, in QoG, there is not column "iso3". No worries, there is a column with "iso3" code, it is just called "ccodealp":

- Rename the variable "ccodealp" to "iso3"

In [ ]:
# Your code here...

For the merging to be successful, we need the columns to have the same name and data type.

- Check that the variable "year" is of integer type, and "iso3" of string (object) type, if not convert them to the proper type.

In [ ]:
# Your code here...

Ok, let's try to merge the QoG and Polity5 dataframe

- Merge the QoG and final polity2 dataframes using the `.merge()` method ([Documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html)). As options, you should use: 
    - `on=["iso3", "year"]` to merge on the iso3 and year columns; 
    - `how="left"` to merge of QoG keys;
    - `validate="one_to_one"` to check if merge keys are unique in both left and right datasets.
- Display your dataframe. How many observations do we have?

In [ ]:
# Your code here...

Our merge was successful. For instance, we have the same number of rows in the merged dataframe and in the QoG ones. However, most of the time, merging is a complex process and you will encounter some issues. For example, if we did not have removed duplicates in Polity5, then it would have failed! (You can check that by re-running all cells in this notebook except the section on removing duplicates) 

We made great progress but our cleaning is not over: for instance, for some countries like South Vietnam we do not have polity2 values. 

The next step would be to select some ingredients (variables) from QoG, deal with NaN and other potential issues, and then select a balanced dataset. However, for this walkthough, we'll be satisfied with what we have achieved so far, and export our result.

- Save the clean merged dataframe as a csv

In [ ]:
# Your code here...

### Further practice [optional] <a name="practising-qog"></a>

- Check [QoG codebook](https://www.qogdata.pol.gu.se/data/codebook_ei_sept21_august2023.pdf) and select 2 variables of your choice
- Extract in a new dataframe the columns 'iso3', 'year', 'cname_qog', 'polity2', and the two variables you previously selected
- Rename the column "cname_qog" as "country"
- Deal with missing values and other issues
- Plot a map of the number of observations per countries

In [ ]:
# Your code here...

## Other dataset to explore <a name="data"></a>

Here are several other datasets that could be useful for your projects, feel free to explore them!
- [World Values Survey: Cross-national](https://www.worldvaluessurvey.org/wvs.jsp), time series indicators of human beliefs and values
- [Global Preference Survey](https://www.briq-institute.org/global-preferences/home): dataset on risk and time preferences, positive and negative reciprocity, altruism, and trust (country- and individual- level data)
- [FAOSTAT](https://www.fao.org/faostat/en/#home) and [GAEZ Data Portal](https://gaez.fao.org/): Food and agriculture data
- [IEA](https://www.iea.org/data-and-statistics/data-sets) data: Energy data
- [Earth Data](https://www.earthdata.nasa.gov/), NASA Earth Observation Data
- [Global Health Observatory](https://www.who.int/data/gho): Health data
- [OECD Data](https://data.oecd.org/): indicators for OECD countries
- [Eurostat](https://ec.europa.eu/eurostat/data/database): large set of datasets for European countries

You can also search and access a large variety of dataset on [Google Dataset Search](https://datasetsearch.research.google.com/), [Kaggle](https://www.kaggle.com/datasets), [OpenML](https://www.openml.org/search?type=data&sort=runs&status=active), and [HuggingFace](https://huggingface.co/datasets).

Whenever you use an existing dataset, **make sure to properly reference the authors!**

Otherwise, have fun in your data science journey and always remember to complain about data cleaning...